// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QyonAdventureWorks.Infra.Context;

namespace QyonAdventureWorks.Infra.Migrations
{
    [DbContext(typeof(QylonDbContext))]
    [Migration("20230309194957_CriacaoBDQylon")]
    partial class CriacaoBDQylon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QyonAdventureWorks.Domain.Entities.Competidor", b =>
                {
                    b.Property<int>("CompetidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sexo")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("TemperaturaMediaCorpo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompetidorId");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("QyonAdventureWorks.Domain.Entities.HistoricoCorrida", b =>
                {
                    b.Property<int>("HistoricoCorridaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompetidorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCorrida")
                        .HasColumnType("datetime2");

                    b.Property<int>("PistaCorridaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TempoGasto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistoricoCorridaId");

                    b.ToTable("HistoricoCorrida");
                });

            modelBuilder.Entity("QyonAdventureWorks.Domain.Entities.PistaCorrida", b =>
                {
                    b.Property<int>("PistaCorridaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(50)");

                    b.HasKey("PistaCorridaId");

                    b.ToTable("PistaCorrida");
                });
#pragma warning restore 612, 618
        }
    }
}
